<?php

function movie_theme($existing, $type, $theme, $path) {
  return [
    'movie_theme_hook' => [
      'render element' => 'children',
      'variables' => [
        'movie' => 'Selected movie',
        'disabledDays' => 'Disabled days'
      ],
    ],
    'movie_reservation_theme_hook' => [
      'render element' => 'children',
      'variables' => [
        'movies' => 'List of movies',
        'genres' => 'List of genres',
        'selectedGenre' => 'Selected genre'
      ],
    ],
    'all_reservations_theme_hook' => [
      'render element' => 'children',
      'variables' => [
        'reservations' => 'List of reservations',
        'selectedSort' => 'Selected sort'
      ],
    ],
  ];
}

function movie_preprocess_node__page(array &$variables) : void {
  $variables['#attached']['library'][] = 'movie/movie';
}

function movie_preprocess_views_view_fields(&$variables) {
  $variables['params']['parameter_name'] = $_GET['parameter_name'];
}
