<?php

function movie_theme($existing, $type, $theme, $path) {
  return [
    'movie_theme_hook' => [
      'render element' => 'children',
      'variables' => [
        'movie' => 'Selected movie',
      ],
    ],
    'movie_reservation_theme_hook' => [
      'render element' => 'children',
      'variables' => [
        'movies' => 'List of movies',
        'genres' => 'List of genres',
        'selectedGenre' => 'Selected genre'
      ],
    ],
  ];
}

function movie_preprocess_node__page(array &$variables) : void {
  $variables['#attached']['library'][] = 'movie/movie';
}

function movie_preprocess_views_view_fields(&$variables) {

  // Retrieve an array which contains the path parameters.
  $variables['params']['parameter_name'] = $_GET['parameter_name'];
}
